name: altura
description: "Altura è un'app per appassionati di droni, che consente di trovare e condividere luoghi dove volare, visualizzare normative e contenuti utili."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.3.2
  location: ^8.0.0
  cloud_firestore: ^5.5.0
  flutter_open_app_settings: ^0.1.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  timeago: ^3.2.2
  http: ^1.3.0
  shared_preferences: ^2.5.2
  firebase_messaging: ^15.2.4
  firebase_in_app_messaging: ^0.8.1+4
  geocoding: ^3.0.0
  geolocator: ^13.0.3
  google_sign_in: ^6.3.0
  fluttertoast: ^8.2.12
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.3.1
  geoflutterfire_plus: ^0.0.32
  file_picker: ^10.0.0
  flutter_map: ^8.1.1
  share_plus: ^10.1.4
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/google-icon.png
    - assets/drone.png
    - assets/drone2.png
    - assets/logo/altura_logo_static.png
    - assets/logo/altura_logo_loader.png
    - assets/logo/app_icon.png
    - assets/onboarding/background_onboarding.png
    - assets/onboarding/background_onboarding2.jpg
    - assets/onboarding/background_onboarding3.jpeg
    - assets/onboarding/background_onboarding4.jpg


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png"

flutter_native_splash:
  color: "#0A2342"
  image: assets/logo/altura_logo_static.png
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
